#! /usr/bin/ruby

## Copyright 2009, Joe Williams <joe@joetify.com>
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal in the Software without
## restriction, including without limitation the rights to use,
## copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following
## conditions:
##
## The above copyright notice and this permission notice shall be
## included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
## EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
## OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
## NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
## HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
## WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
## OTHER DEALINGS IN THE SOFTWARE.


require 'rubygems'
require 'right_aws'
require 'socket'
require 'fadvise'

tens3_config = YAML.load(File.open(ARGV[0]))

AWS_KEY = tens3_config['amazon_access_key_id']
AWS_SECRET = tens3_config['amazon_secret_access_key']
BUCKET_NAME = tens3_config['bucket_name']

S3 = RightAws::S3Interface.new(AWS_KEY, AWS_SECRET)
def main
  if ARGV.length != 4
    puts "tens3_get usage:\n# tens3_get CONFIG BACKUPDATE REMOTEFILENAME LOCALFILEWITHPATH"
  else
    s3 = RightAws::S3Interface.new(AWS_KEY, AWS_SECRET)
    remote_file_name = "#{ARGV[1]}_#{ARGV[2]}"
    local_file_name = "#{ARGV[3]}"

    puts "[ #{Time.now} ] IFNO :: Creating local file at #{local_file_name}"
    file = File.open(local_file_name, File::CREAT|File::RDWR)
    file.fadvise(0, 0, :dont_need)

    puts "[ #{Time.now} ] INFO :: Streaming #{remote_file_name} from S3 to #{local_file_name}"
    rhdr = s3.get(BUCKET_NAME, remote_file_name) do |chunk|
      file.write(chunk)
    end

    file.close
  end
end

main
